project_id = "sbyfgresripeilehcoru"

[functions.create-order]
verify_jwt = false

[functions.order-emails]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.storage-cleanup]
verify_jwt = true

[functions.get-service-key]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false
